export class Container {
  companyName:string;
  companyNo:number;
  incdate:string;
  address:string;
  phoneno:number;
  faxno:number;
  panno:string;
  language:string;
  email:string;
  website:string;
  countryname:object;
  state:object;
  currency:string;
  GSTregistered:string;
  GSTno:string;
  gstRegisteredDate:string;
  companylogo:object;
  yearclosing:any;
  closingMethod:string;
  startperiod:string;
  closeperiod:number;
  ExtensionPeriod:string;
  startyear:any;
  endyear:any;
  Extension:string;
  gstreturnalertdue:string;
}
